### ISSUE TITLE
simplifying massaging names for splitstree

### ISSUE THREAD

**Issue by HedvigS** [IVS-UZH/RSplitsTree#1]
Just a small suggestion, nothing big. 

I think `[this](https://github.com/IVS-UZH/RSplitsTree/blob/172a22dd2e9adb312b3cfcc658b73d798e028947/R/splitstree.R#L60
)` could be simplified by using

```
  stringi::stri_trans_general("latin-ascii") %>% 
  str_replace_all("\\(", "") %>%  
  str_replace_all("\\)", "") %>% 
  str_replace_all("\\-", "") %>% 
 str_replace_all(" ", "_")  %>% 
  str_replace_all("\\'", "?") 
```

**Comment by tzakharko** [comment]
@HedvigS thanks for the suggestion! You are absolutely right (and your code is likely more robust anyway), but this package is basically in maintenance status so I am a bit reluctant to make significant changes, especially if they involve adding heavy dependencies like stringi. 

Please reopen this ticket if you are running into practical issues!

**Comment by HedvigS** [comment]
No worries, understood!
